# Generated by Django 4.1.6 on 2023-02-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_anunciante'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='anuciante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.anunciante'),
            preserve_default=False,
        ),
    ]
